services:
  client:
    image: client
    container_name: crm_client
    ports:
      - ${NX_APP_PORT}:80
  server:
    image: server
    container_name: crm_server
    ports:
      - "${NX_SERVER_PORT}:${NX_SERVER_PORT}"
      - "${NX_SOCKET_NOTIFICATIONS_PORT}:${NX_SOCKET_NOTIFICATIONS_PORT}"
      - "${NX_SOCKET_STREAMING_UPDATE_PORT}:${NX_SOCKET_STREAMING_UPDATE_PORT}"
    env_file:
      - ./.env
